### ISSUE TITLE
Knowledge base milestone

### ISSUE THREAD

**Issue by RamiAwar** [RamiAwar/dataline#283]
### Privileged issue

- [X] I'm @ramiawar or he asked me directly to create an issue here.

### Issue Content

Requirements:
- [ ] Be able to query massive databases with hundreds of tables and still select the proper tables automatically
- [ ] Be able to save SQL queries as "examples" to assist the LLM in similar cases
